const companies = [
  {
    "name": "アークシステム（株）",
    "zip": "720-0032",
    "city": "福山市",
    "address": "三吉町南2-6-31",
    "tel": "084-923-6300",
    "url": "http://www.arcsystem.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ＩＨＩビジネスサポート 呉事業所",
    "zip": "737-0027",
    "city": "呉市",
    "address": "昭和町2-1 （株）IHI呉事業所内",
    "tel": "0823-24-4181",
    "url": "http://www.ihi.co.jp/ihibs/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ISK",
    "zip": "734-0044",
    "city": "広島市南区",
    "address": "西霞町2-31 SKビル301",
    "tel": "082-207-3200",
    "url": "https://isk-keibi.jimdofree.com/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "IGO-SECURITY（株）",
    "zip": "730-0045",
    "city": "広島市中区",
    "address": "鶴見町3-21 NCビル",
    "tel": "090-3639-2273",
    "url": "https://igo-security.com/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "青葉警備保障（株）",
    "zip": "720-0076",
    "city": "福山市",
    "address": "本庄町中1-34-1",
    "tel": "084-921-3472",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）安芸管理サービス",
    "zip": "736-0032",
    "city": "安芸郡海田町",
    "address": "南幸町10-6 AKS bldg.",
    "tel": "082-824-2277",
    "url": "http://www.aki-management.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）アサヒセキュリティ 中国本部",
    "zip": "733-0841",
    "city": "広島市西区",
    "address": "井口明神1-1-24",
    "tel": "082-270-3944",
    "url": "http://www.assjapan.co.jp/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": true,
    "bodyguard": false
  },
  {
    "name": "（株）アサヒファシリティズ 広島支店",
    "zip": "730-0015",
    "city": "広島市中区",
    "address": "橋本町10-10 広島インテス",
    "tel": "082-222-7500",
    "url": "http://asahifm.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）アシスト",
    "zip": "731-0138",
    "city": "広島市安佐南区",
    "address": "祇園5-3-41",
    "tel": "082-850-3723",
    "url": "http://assist-safety.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）アドバンスオオヤマ",
    "zip": "728-0022",
    "city": "三次市",
    "address": "西酒屋町692-2",
    "tel": "0824-63-0345",
    "url": "",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）アビリティ・サポート",
    "zip": "733-0007",
    "city": "広島市西区",
    "address": "大宮1-1-5",
    "tel": "082-537-2525",
    "url": "http://kk-ability.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ARIS警備",
    "zip": "730-0845",
    "city": "広島市中区",
    "address": "舟入川口町3-14",
    "tel": "082-554-5101",
    "url": "https://ariskeibi.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）安全システム情報センター",
    "zip": "730-0842",
    "city": "広島市中区",
    "address": "舟入中町5-13",
    "tel": "082-234-7277",
    "url": "http://www.ssic.co.jp/company.html",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）イズミテクノ",
    "zip": "733-0833",
    "city": "広島市西区",
    "address": "商工センター2-3-1 エクセルビル3F",
    "tel": "082-270-2750",
    "url": "http://www.izumi-techno.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "イナリ警備情報（株）",
    "zip": "720-0076",
    "city": "福山市",
    "address": "本庄町中2-7-6",
    "tel": "084-925-2071",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）エイチ・アイカンパニー",
    "zip": "722-0014",
    "city": "尾道市",
    "address": "新浜1-14-31 金属ビル7F",
    "tel": "0848-21-2731",
    "url": "http://www.ne.jp/asahi/hic/company/gaiyou.html",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "HSCセキュリティ合同会社",
    "zip": "733-0021",
    "city": "広島市西区",
    "address": "上天満町9-2 免出ビル202",
    "tel": "082-294-7535",
    "url": "https://2rwwvoia.jbplt.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）エイチピーピー",
    "zip": "730-0041",
    "city": "広島市中区",
    "address": "小町3-25 三共広島ビル9階",
    "tel": "082-258-4920",
    "url": "http://www.hpp-ltd.com/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）SIM",
    "zip": "738-0024",
    "city": "廿日市市",
    "address": "新宮1-10-62-3階",
    "tel": "0829-30-9469",
    "url": "https://sim-hiroshima.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "NXキャッシュ・ロジスティクス㈱ 中国支店 広島センター",
    "zip": "730-0825",
    "city": "広島市中区",
    "address": "光南6-2-25",
    "tel": "082-248-6605",
    "url": "https://www.nxcl.co.jp/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": true,
    "bodyguard": false
  },
  {
    "name": "（株）エネルギア L&B パートナーズ",
    "zip": "730-0041",
    "city": "広島市中区",
    "address": "小町4-33",
    "tel": "082-242-7807",
    "url": "https://www.energia-lbp.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）エムケイ興産",
    "zip": "737-0046",
    "city": "呉市",
    "address": "中通1-3-16",
    "tel": "0823-25-6221",
    "url": "http://www.mk-kousan.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）Ｍサポート",
    "zip": "734-0033",
    "city": "広島市南区",
    "address": "丹那新町1-20",
    "tel": "082-207-1521",
    "url": "https://m-support.miyaken1041.jp/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）エール警備保障",
    "zip": "732-0055",
    "city": "広島市東区",
    "address": "蟹屋町16-34",
    "tel": "082-258-4057",
    "url": "https://yell-security.co.jp",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）オオケン",
    "zip": "732-0826",
    "city": "広島市南区",
    "address": "松川町5-9",
    "tel": "082-263-0025",
    "url": "http://www.oken-co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）オオサキ",
    "zip": "725-0301",
    "city": "豊田郡大崎上島町",
    "address": "中野5522-10",
    "tel": "0846-64-4070",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "オノギ警備保障（株）",
    "zip": "729-0104",
    "city": "福山市",
    "address": "松永町3-3-6",
    "tel": "084-934-1147",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）尾道警備保障",
    "zip": "729-0141",
    "city": "尾道市",
    "address": "高須町4836-17",
    "tel": "0848-46-7010",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "ガードサービス（有）",
    "zip": "732-0825",
    "city": "広島市南区",
    "address": "金屋町9-4",
    "tel": "082-506-2005",
    "url": "",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ガードリサーチ",
    "zip": "730-0805",
    "city": "広島市中区",
    "address": "十日市町2-5-12",
    "tel": "082-291-6101",
    "url": "https://guard-research.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）カルフート",
    "zip": "732-0052",
    "city": "広島市東区",
    "address": "光町2-4-8",
    "tel": "082-263-7684",
    "url": "http://www.culfute.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）カルフート警備保障",
    "zip": "738-0034",
    "city": "廿日市市",
    "address": "宮内4349-1-106",
    "tel": "0829-30-8025",
    "url": "http://www.culfute-keibi.com/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "企業警備保障（株）",
    "zip": "732-0824",
    "city": "広島市南区",
    "address": "的場町1-3-17",
    "tel": "082-264-1727",
    "url": "http://www.kigyokeibi.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": true
  },
  {
    "name": "（株）CAST ONE",
    "zip": "738-0031",
    "city": "廿日市市",
    "address": "原853",
    "tel": "0829-30-0185",
    "url": "https://www.cast-one.biz/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "協立建物管理（株）",
    "zip": "732-0052",
    "city": "広島市東区",
    "address": "光町1-13-20 ディア光町ビル3F",
    "tel": "082-264-5789",
    "url": "http://kyoritu-tk.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）クマヒラセキュリティ",
    "zip": "734-0004",
    "city": "広島市南区",
    "address": "宇品神田5-23-20",
    "tel": "082-256-0010",
    "url": "https://www.s-kumahira.net/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "くれしんビジネスサービス（株）",
    "zip": "737-0045",
    "city": "呉市",
    "address": "本通2-2-15",
    "tel": "0823-22-5444",
    "url": "http://www.kure-shinkin.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": true,
    "bodyguard": false
  },
  {
    "name": "（株）くれせん",
    "zip": "737-0811",
    "city": "呉市",
    "address": "西中央4-6-3",
    "tel": "0823-23-7111",
    "url": "http://www.kuresen.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）クレネット",
    "zip": "732-0052",
    "city": "広島市東区",
    "address": "光町2-9-30",
    "tel": "082-263-0568",
    "url": "http://cle-net.info/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）KIG広島",
    "zip": "730-0002",
    "city": "広島市中区",
    "address": "白島中町9-1 松中ビル202",
    "tel": "082-555-9938",
    "url": "https://kig-hiroshima.jp/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）KSP・WEST 広島営業所",
    "zip": "732-0052",
    "city": "広島市東区",
    "address": "光町1-11-5 チサンマンション広島311",
    "tel": "082-263-0021",
    "url": "https://ksp-kokusai.co.jp/west/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）警研社",
    "zip": "731-0103",
    "city": "広島市安佐南区",
    "address": "緑井4-30-5",
    "tel": "082-962-9922",
    "url": "http://keikensya.jp/index.html",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ケイビ",
    "zip": "730-0051",
    "city": "広島市中区",
    "address": "大手町4-5-18",
    "tel": "082-258-2588",
    "url": "http://www.keibi1983.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "警備開発（株）",
    "zip": "734-0007",
    "city": "広島市南区",
    "address": "皆実町1-8-28",
    "tel": "082-255-5595",
    "url": "http://www.keibikaihatsu.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": true,
    "valuables": true,
    "bodyguard": false
  },
  {
    "name": "警備保障イーグル88",
    "zip": "723-0052",
    "city": "三原市",
    "address": "皆実1-13-3",
    "tel": "0848-62-3478",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "警備保障エナジー（株）",
    "zip": "722-0052",
    "city": "尾道市",
    "address": "山波町473-1",
    "tel": "0848-20-2758",
    "url": "https://keibihosyo-energy.com/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ケーシーエル",
    "zip": "739-0025",
    "city": "東広島市",
    "address": "西条中央6-31-38 セラフィクビル2階",
    "tel": "082-431-5578",
    "url": "https://kcl-gr.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ケーブロック",
    "zip": "731-5122",
    "city": "広島市佐伯区",
    "address": "五日市中央2-4-18-101",
    "tel": "082-258-5111",
    "url": "https://k-brock.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ケンセイ舎",
    "zip": "721-0971",
    "city": "福山市",
    "address": "蔵王町162-1",
    "tel": "084-941-6888",
    "url": "https://kenseigroup.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ケントク 中国支社",
    "zip": "732-0821",
    "city": "広島市南区",
    "address": "大須賀町17-5 シャンボール広交2F",
    "tel": "082-264-0091",
    "url": "http://www.kentoku.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）コアズ 広島支社",
    "zip": "730-0051",
    "city": "広島市中区",
    "address": "大手町3-1-3 I・T大手町ビル",
    "tel": "082-240-0182",
    "url": "https://corps-inc.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）合人社計画研究所 広島支店",
    "zip": "730-0036",
    "city": "広島市中区",
    "address": "袋町4-31 合人社広島袋町ビル",
    "tel": "082-247-7475",
    "url": "http://www.gojin.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）広成開発",
    "zip": "732-0052",
    "city": "広島市東区",
    "address": "光町2-7-17",
    "tel": "082-263-9049",
    "url": "https://www.koseikaihatsu.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）合同警備保障",
    "zip": "720-0822",
    "city": "福山市",
    "address": "川口町5-20-15",
    "tel": "084-954-9800",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "合同産業（株）",
    "zip": "730-0051",
    "city": "広島市中区",
    "address": "大手町2-7-10",
    "tel": "082-245-2333",
    "url": "http://www.godosangyo.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "広陽ビル管理（株）",
    "zip": "730-0011",
    "city": "広島市中区",
    "address": "基町20-7",
    "tel": "082-221-6411",
    "url": "http://www.kouyou-bk.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）コーエー",
    "zip": "737-0045",
    "city": "呉市",
    "address": "本通6-7-10",
    "tel": "0823-23-5695",
    "url": "http://www.koeihiroshima.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "国際セーフティー（株）広島支社",
    "zip": "730-0802",
    "city": "広島市中区",
    "address": "本川町2-1-13 和光パレス21 2F",
    "tel": "082-293-5931",
    "url": "https://www.kokusai-safety.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "国内セフティ（株）",
    "zip": "739-0042",
    "city": "東広島市",
    "address": "西条町西条東1024-3 灘田ビル103",
    "tel": "082-437-5371",
    "url": "https://kokunai-safety.jp/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "互光建物管理（株）広島支店",
    "zip": "730-0041",
    "city": "広島市中区",
    "address": "小町1-25 ビル博丈平和大通り3F",
    "tel": "082-242-8661",
    "url": "https://www.goko-tatemono.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）コムレイズ",
    "zip": "733-0012",
    "city": "広島市西区",
    "address": "中広町2-4-3",
    "tel": "082-909-2466",
    "url": "https://cmrd.net/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）サポートサービス",
    "zip": "733-0012",
    "city": "広島市西区",
    "address": "中広町3-2-4",
    "tel": "082-297-6110",
    "url": "",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "サンケイ（株）",
    "zip": "733-0812",
    "city": "広島市西区",
    "address": "己斐本町2-6-19",
    "tel": "082-507-0671",
    "url": "https://www.sankei-gr.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）サンセイ",
    "zip": "731-0102",
    "city": "広島市安佐南区",
    "address": "川内5-32-16",
    "tel": "082-879-7571",
    "url": "http://kk-sansei.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）サンテス",
    "zip": "721-0963",
    "city": "福山市",
    "address": "南手城町3-25-22",
    "tel": "084-926-1113",
    "url": "https://y-santes.amebaownd.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）山陽セフティ 福山営業所",
    "zip": "720-0066",
    "city": "福山市",
    "address": "三之丸町13-18 リムフクヤマ第3駐車場1F",
    "tel": "084-927-2007",
    "url": "http://www.sanyo-safety.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": false,
    "valuables": true,
    "bodyguard": false
  },
  {
    "name": "山陽都市管理（株）",
    "zip": "733-0821",
    "city": "広島市西区",
    "address": "庚午北1-16-10",
    "tel": "082-942-3955",
    "url": "http://www.sanyo-toshi.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "サンライトセキュリティー（株）",
    "zip": "733-0005",
    "city": "広島市西区",
    "address": "三滝町6-1",
    "tel": "082-509-2020",
    "url": "https://sunlight-s-recruit.jp/-/top/index.html",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）CGSコーポレーション 広島支店",
    "zip": "731-0102",
    "city": "広島市安佐南区",
    "address": "川内5-15-7",
    "tel": "082-962-6188",
    "url": "http://www.cgs1.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ジェイアール西日本 総合ビルサービス 広島支店",
    "zip": "732-0826",
    "city": "広島市南区",
    "address": "松川町1-19 太陽生命広島松川町ビル5F",
    "tel": "082-264-4941",
    "url": "http://www.jr-bs.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": true,
    "valuables": true,
    "bodyguard": true
  },
  {
    "name": "JFE西日本ジーエス（株）",
    "zip": "721-0931",
    "city": "福山市",
    "address": "鋼管町1 JFEスチール西日本製鉄所福山地区内",
    "tel": "084-943-7358",
    "url": "http://www.jfe-ngs.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）J-POWER ビジネスサービス 竹原事業所",
    "zip": "729-2315",
    "city": "竹原市",
    "address": "忠海長浜2-1-1",
    "tel": "0846-24-1911",
    "url": "http://www.jpbs.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "持続未来（株）",
    "zip": "730-0035",
    "city": "広島市西区",
    "address": "南観音八丁目10-28",
    "tel": "082-232-0533",
    "url": "http://www.jizoku-mirai.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）實徳コーポレーション",
    "zip": "722-1114",
    "city": "世羅郡世羅町",
    "address": "大字東神崎368-21",
    "tel": "0847-25-5271",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）ジップ",
    "zip": "721-0942",
    "city": "福山市",
    "address": "引野町1-24-9",
    "tel": "084-946-6535",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）シナジー コミュニケーションズ",
    "zip": "739-0041",
    "city": "東広島市",
    "address": "西条町寺家6840-1 アロフトユーカリ1階",
    "tel": "0120-424-430",
    "url": "https://sygcommunications.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "シンクアイ（株）",
    "zip": "739-2105",
    "city": "東広島市",
    "address": "高屋町檜山779-3",
    "tel": "082-426-3500",
    "url": "https://thinkinc.co.jp/business/eye/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）Joyコーポレーション",
    "zip": "731-0122",
    "city": "広島市安佐南区",
    "address": "中筋3-26-13",
    "tel": "082-555-1200",
    "url": "https://joy-gr.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "シンライト（株）",
    "zip": "731-5151",
    "city": "広島市佐伯区",
    "address": "五日市町上河内298-1",
    "tel": "082-926-2330",
    "url": "https://shine-light.jp/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "新和ビル・サービス（株）",
    "zip": "722-0025",
    "city": "尾道市",
    "address": "栗原東1-6-29",
    "tel": "0848-23-9102",
    "url": "http://www.shinwabs.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）酔翁アイシン警備",
    "zip": "736-0005",
    "city": "安芸郡海田町",
    "address": "畝2-13-4",
    "tel": "082-822-5611",
    "url": "https://www.aishinkeibi.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）スター",
    "zip": "733-0007",
    "city": "広島市西区",
    "address": "大宮1-1-38",
    "tel": "082-537-0395",
    "url": "",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）スリーエス 広島営業所",
    "zip": "732-0052",
    "city": "広島市東区",
    "address": "光町2-12-10 日宝光町ビル3F",
    "tel": "082-567-8660",
    "url": "https://www.3-s.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "星光ビル管理（株）広島営業所",
    "zip": "732-0052",
    "city": "広島市東区",
    "address": "光町1-10-19",
    "tel": "082-207-1516",
    "url": "https://www.saycogroup.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）セキュリティプロ",
    "zip": "730-0813",
    "city": "広島市中区",
    "address": "住吉町4-4",
    "tel": "082-545-7313",
    "url": "http://securitypro.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": true
  },
  {
    "name": "セコムスタティック西日本（株）",
    "zip": "730-0022",
    "city": "広島市中区",
    "address": "銀山町3-1 ひろしまハイビル21",
    "tel": "082-247-9156",
    "url": "https://www.secom.co.jp/corporate/outline/security.html",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "セコム（株）中国本部",
    "zip": "730-0022",
    "city": "広島市中区",
    "address": "銀山町3-1 ひろしまハイビル21",
    "tel": "082-243-3111",
    "url": "http://www.secom.co.jp/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": false,
    "crowd": false,
    "valuables": true,
    "bodyguard": false
  },
  {
    "name": "（株）セノン 広島支社",
    "zip": "730-0051",
    "city": "広島市中区",
    "address": "大手町2-8-5 合人社広島大手町ビル3F",
    "tel": "082-249-1327",
    "url": "http://www.senon.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": true,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "セフト（株）",
    "zip": "733-0012",
    "city": "広島市西区",
    "address": "中広町1-12-16",
    "tel": "082-535-5677",
    "url": "http://www.sefto.co.jp/",
    "facility": true,
    "patrol": false,
    "security": true,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）セントラル警備",
    "zip": "733-0013",
    "city": "広島市西区",
    "address": "横川新町14-12",
    "tel": "082-209-3888",
    "url": "https://central-keibi.net/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "セントラル警備保障（株） 広島支社",
    "zip": "732-0052",
    "city": "広島市東区",
    "address": "光町1-10-19 日本生命広島光町ビル",
    "tel": "082-263-5688",
    "url": "https://www.we-are-csp.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）セントラル警備保障 福山支店",
    "zip": "720-0838",
    "city": "福山市",
    "address": "瀬戸町大字山北363-1",
    "tel": "084-952-1134",
    "url": "http://central-keibi.com/corporation.html",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "セントラルライフ（株） 広島営業所",
    "zip": "730-0013",
    "city": "広島市中区",
    "address": "八丁堀15-10 セントラルビル5F",
    "tel": "082-227-1776",
    "url": "http://www.centrallife.co.jp/corp.html",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）全日警 広島支社",
    "zip": "730-0012",
    "city": "広島市中区",
    "address": "上八丁堀4-1 アーバンビューグランドタワー6F",
    "tel": "082-222-7780",
    "url": "http://www.zennikkei.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": true,
    "machine": true,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）センビ",
    "zip": "733-0823",
    "city": "広島市西区",
    "address": "庚午南2-33-24",
    "tel": "082-275-1701",
    "url": "http://www.senbi.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ソルコムビジネスサービス",
    "zip": "733-0034",
    "city": "広島市西区",
    "address": "南観音町3-6",
    "tel": "082-554-5133",
    "url": "http://www.solcom-bs.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）第一ビルサービス",
    "zip": "730-0051",
    "city": "広島市中区",
    "address": "大手町5-3-12",
    "tel": "082-248-1601",
    "url": "https://www.midori-gr.com/daiichibs/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）太栄警備",
    "zip": "733-0012",
    "city": "広島市西区",
    "address": "中広町3-4-1 ニュー三進ビル1F",
    "tel": "082-532-6260",
    "url": "https://taieikeibi.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "太平ビルサービス（株） 広島支店",
    "zip": "730-0042",
    "city": "広島市中区",
    "address": "国泰寺町1-7-40 APエルテージ国泰寺ビル7F",
    "tel": "082-244-1592",
    "url": "http://www.taihei-bs.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "大宝警備（有）",
    "zip": "729-3101",
    "city": "福山市",
    "address": "新市町戸手1692",
    "tel": "0847-51-4557",
    "url": "https://taihou-keibi.com/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）太陽警備",
    "zip": "720-0843",
    "city": "福山市",
    "address": "赤坂町大字赤坂1194-2",
    "tel": "084-952-1302",
    "url": "https://taiyoukeibi.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）タック",
    "zip": "731-1526",
    "city": "山県郡北広島町",
    "address": "本地2652",
    "tel": "0826-72-8585",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）チューゲイ",
    "zip": "727-0012",
    "city": "庄原市",
    "address": "中本町1-3-31",
    "tel": "0824-72-0655",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "中電環境テクノス（株）",
    "zip": "730-0041",
    "city": "広島市中区",
    "address": "小町4-33",
    "tel": "082-242-0298",
    "url": "http://www.e-ckt.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "中武警備保障（株）",
    "zip": "721-0942",
    "city": "福山市",
    "address": "引野町5-10-22",
    "tel": "084-943-5522",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）テイケイ西日本",
    "zip": "730-0004",
    "city": "広島市中区",
    "address": "東白島町19-77",
    "tel": "082-227-6584",
    "url": "http://www.tei-kei-wj.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": true,
    "bodyguard": true
  },
  {
    "name": "（株）ティスコ",
    "zip": "732-0053",
    "city": "広島市東区",
    "address": "若草町10-12 日宝若草町ビル",
    "tel": "082-264-0188",
    "url": "https://www.tss-co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "テルウェル西日本（株） 中国支店",
    "zip": "730-8585",
    "city": "広島市中区",
    "address": "基町6-78 基町クレド パセーラ10F",
    "tel": "082-227-5246",
    "url": "http://www.telwel-west.co.jp/chugoku/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）東警セキュリティー",
    "zip": "739-0044",
    "city": "東広島市",
    "address": "西条町下見4678-3",
    "tel": "082-424-8130",
    "url": "http://toukei.works/top",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）東部警備保障",
    "zip": "720-0017",
    "city": "福山市",
    "address": "千田町2-35-17",
    "tel": "084-955-7766",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "東宝ビル管理（株）中国支社",
    "zip": "730-0013",
    "city": "広島市中区",
    "address": "八丁堀2-31 広島鴻池ビル",
    "tel": "082-227-9014",
    "url": "http://www.toho-bm.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "東洋警備保障（株）",
    "zip": "730-0052",
    "city": "広島市中区",
    "address": "千田町2-1-16",
    "tel": "082-248-3050",
    "url": "https://toyo-sac.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": true,
    "bodyguard": true
  },
  {
    "name": "東和セキュリティサービス（株）",
    "zip": "732-0822",
    "city": "広島市南区",
    "address": "松原町3-1 エキシティセンターM201",
    "tel": "082-263-4033",
    "url": "http://www.towass.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）トエルセキュリティ",
    "zip": "731-0221",
    "city": "広島市安佐北区",
    "address": "可部4-19-6",
    "tel": "082-554-7747",
    "url": "https://www.to-line.jp/tol-s",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "都市道路開発（株）",
    "zip": "730-0802",
    "city": "広島市中区",
    "address": "本川町2-6-21 清水ビル2F",
    "tel": "082-293-4580",
    "url": "https://www.toshidouro.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ナビコン",
    "zip": "720-1133",
    "city": "福山市",
    "address": "駅家町近田461",
    "tel": "084-970-1557",
    "url": "https://www.instagram.com/navicon.security",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "西日本高速道路 エンジニアリング中国（株）",
    "zip": "733-0037",
    "city": "広島市西区",
    "address": "西観音町2-1 第3セントラルビル",
    "tel": "082-532-1430",
    "url": "http://www.w-e-chugoku.co.jp/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "西日本高速道路 メンテナンス中国（株）",
    "zip": "732-0053",
    "city": "広島市東区",
    "address": "若草町12-1 アクティブインターシティ広島オフィス棟12F",
    "tel": "082-568-2288",
    "url": "http://www.w-m-chugoku.co.jp/index.html",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "西日本テクニカル ハイウェイ（株）",
    "zip": "730-0851",
    "city": "広島市中区",
    "address": "榎町6-9",
    "tel": "082-576-3048",
    "url": "https://www.technical-inc.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）西日本ファシリティー",
    "zip": "721-0974",
    "city": "福山市",
    "address": "東深津町7-15-2",
    "tel": "084-922-2199",
    "url": "https://www.nn-facility.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）日警セフティ",
    "zip": "731-0143",
    "city": "広島市安佐南区",
    "address": "長楽寺1-8-26",
    "tel": "082-832-7000",
    "url": "http://nikkeigroup.net/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ＮＩＣＣＯサポート",
    "zip": "731-0102",
    "city": "広島市安佐南区",
    "address": "川内2-5-20",
    "tel": "082-870-2501",
    "url": "https://smd.niccocc.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "日鉄ビジネスサービス（株）瀬戸内事業所",
    "zip": "671-1116",
    "city": "姫路市広畑区",
    "address": "正門通4-9-6 (呉市昭和町11-1 日本製鉄内）",
    "tel": "079-280-6511",
    "url": "https://nsb.nipponsteel.com",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ニットー",
    "zip": "730-0844",
    "city": "広島市中区",
    "address": "舟入幸町15-3",
    "tel": "082-233-0551",
    "url": "http://www.kk-nitto.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": true,
    "bodyguard": false
  },
  {
    "name": "日本管財（株）広島営業所",
    "zip": "730-0013",
    "city": "広島市中区",
    "address": "八丁堀15-8 三菱UFJ信託銀行広島ビル7F",
    "tel": "082-222-5841",
    "url": "http://www.nkanzai.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）日本斎苑",
    "zip": "728-0013",
    "city": "三次市",
    "address": "十日市東2-3-8",
    "tel": "0824-65-3411",
    "url": "https://nihon-saien.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ネクストガードサービス",
    "zip": "736-0032",
    "city": "安芸区",
    "address": "上瀬野南1-1990-2",
    "tel": "05036230114",
    "url": "https://next-gs.jp/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ハウディ",
    "zip": "731-0137",
    "city": "広島市安佐南区",
    "address": "山本4-10-5",
    "tel": "082-846-0831",
    "url": "",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": true,
    "bodyguard": false
  },
  {
    "name": "（有）バンセイ",
    "zip": "731-0103",
    "city": "広島市安佐南区",
    "address": "緑井6-27-3 ふじコーポ102",
    "tel": "082-870-1423",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ビーエルテック",
    "zip": "728-0025",
    "city": "三次市",
    "address": "粟屋町1455-1",
    "tel": "0824-65-1919",
    "url": "https://bltech.jp/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ビサン",
    "zip": "720-2124",
    "city": "福山市",
    "address": "神辺町川南1580-1",
    "tel": "084-965-6676",
    "url": "https://k-bisan.co.jp",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ひまわりセキュリティー",
    "zip": "739-1733",
    "city": "広島市安佐北区",
    "address": "口田南2-1-15",
    "tel": "082-847-3700",
    "url": "https://www.himawari-s.net/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ヒューマックス",
    "zip": "734-0025",
    "city": "広島市南区",
    "address": "東本浦町10-22",
    "tel": "082-282-5361",
    "url": "https://www.humax-inc.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "ビルックス（株）",
    "zip": "737-0004",
    "city": "呉市",
    "address": "阿賀南1-8-49",
    "tel": "0823-74-5963",
    "url": "http://builx.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ヒロエー",
    "zip": "734-0013",
    "city": "広島市南区",
    "address": "出島2-13-35",
    "tel": "082-255-1212",
    "url": "http://www.hiroei.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "ひろしま管財（株）",
    "zip": "730-0051",
    "city": "広島市中区",
    "address": "大手町5-7-17",
    "tel": "082-243-5501",
    "url": "http://hr-kanzai.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": true
  },
  {
    "name": "（株）広島企業",
    "zip": "731-0125",
    "city": "広島市安佐南区",
    "address": "大町西1-24-40",
    "tel": "082-879-2315",
    "url": "http://www.hiroshimakigyo.co.jp",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "広島企業警備保障（株）",
    "zip": "730-0843",
    "city": "広島市中区",
    "address": "舟入本町7-22 平和ビル3F南側",
    "tel": "082-293-1545",
    "url": "http://hk-keibi.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "広島綜警サービス（株）",
    "zip": "731-0113",
    "city": "広島市安佐南区",
    "address": "西原8-2-8 綜警サービスビル",
    "tel": "082-871-2250",
    "url": "http://www.alsok-hss.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": true
  },
  {
    "name": "広島綜合警備保障（株）",
    "zip": "731-0113",
    "city": "広島市安佐南区",
    "address": "西原8-34-3",
    "tel": "082-871-2200",
    "url": "http://www.hsk-inf.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": true,
    "valuables": true,
    "bodyguard": true
  },
  {
    "name": "広島内外美装（株）",
    "zip": "733-0821",
    "city": "広島市西区",
    "address": "庚午北2-16-4",
    "tel": "082-533-8204",
    "url": "https://www.naigai-hd.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）広島リバイン",
    "zip": "733-0011",
    "city": "広島市西区",
    "address": "横川町2-10-13",
    "tel": "082-295-2311",
    "url": "https://www.revain.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "ひろしんビジネスサービス（株）",
    "zip": "730-0043",
    "city": "広島市中区",
    "address": "富士見町3-15",
    "tel": "082-245-0321",
    "url": "http://www.shinkin.co.jp/hiroshin/",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": true,
    "bodyguard": false
  },
  {
    "name": "（株）ヒロハイ",
    "zip": "731-1533",
    "city": "山県郡北広島町",
    "address": "有田1764-1",
    "tel": "0826-73-0573",
    "url": "",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）Figona",
    "zip": "735-0006",
    "city": "安芸郡府中町",
    "address": "本町4-1-14",
    "tel": "082-259-3997",
    "url": "",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）福山パトロール",
    "zip": "726-0012",
    "city": "府中市",
    "address": "中須町943-3",
    "tel": "0847-54-2950",
    "url": "https://fukuyamapatrol.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）フジセキュリティ 広島支社",
    "zip": "730-0044",
    "city": "広島市中区",
    "address": "宝町2-29 西南ビル",
    "tel": "082-258-2795",
    "url": "http://www.fjsec.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "冨士総合（株）",
    "zip": "720-0032",
    "city": "福山市",
    "address": "三吉町南1-13-18",
    "tel": "084-926-0915",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）不二ビルサービス",
    "zip": "733-0002",
    "city": "広島市西区",
    "address": "楠木町4-8-12",
    "tel": "082-962-8917",
    "url": "http://www.fujibiru.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）プラスエス",
    "zip": "731-0102",
    "city": "広島市安佐南区",
    "address": "川内2-19-13 ハイム川内1F",
    "tel": "082-962-4470",
    "url": "https://www.plus-s-official.com",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）ブルーロード警備",
    "zip": "721-0973",
    "city": "福山市",
    "address": "南蔵王町5-20-27",
    "tel": "084-945-7711",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ベッセルテクノサービス",
    "zip": "720-0077",
    "city": "福山市",
    "address": "南本庄3-4-27",
    "tel": "084-923-7535",
    "url": "http://www.vesseltechno.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）保安警備",
    "zip": "733-0007",
    "city": "広島市西区",
    "address": "大宮1-1-7",
    "tel": "082-230-4000",
    "url": "http://www.kk-hoankeibi.co.jp/index.html",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": true,
    "valuables": true,
    "bodyguard": true
  },
  {
    "name": "マツダエース（株）",
    "zip": "735-0028",
    "city": "安芸郡府中町",
    "address": "新地3-1",
    "tel": "082-565-6533",
    "url": "http://www.mazdaace.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "マリンコーポレーション（株）",
    "zip": "737-0029",
    "city": "呉市",
    "address": "宝町4-21",
    "tel": "0823-22-5111",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）丸扇技行",
    "zip": "722-2211",
    "city": "尾道市",
    "address": "因島中庄町3880-1",
    "tel": "0845-26-2256",
    "url": "http://www.g-marusen.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）丸猫",
    "zip": "731-0122",
    "city": "広島市安佐南区",
    "address": "中筋3-27-26",
    "tel": "082-879-2465",
    "url": "https://maruneko.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）三井開発",
    "zip": "739-0025",
    "city": "東広島市",
    "address": "西条中央5-9-14",
    "tel": "082-423-3232",
    "url": "https://mitsui-kaihatsu.co.jp",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）三越伊勢丹 アイムファシリティーズ 広島営業所",
    "zip": "730-0021",
    "city": "広島市中区",
    "address": "胡町5-1",
    "tel": "082-242-3246",
    "url": "https://imi-f.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "三菱電機ビルソリューションズ（株）中国支社",
    "zip": "730-0037",
    "city": "広島市中区",
    "address": "中町7-22 住友生命広島平和大通りビル内",
    "tel": "082-248-1081",
    "url": "http://www.meltec.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "未来アドバンス（株）",
    "zip": "732-0816",
    "city": "広島市南区",
    "address": "比治山本町13-1",
    "tel": "082-250-6070",
    "url": "http://www.mirai-advance.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）モリタ美研",
    "zip": "723-0044",
    "city": "三原市",
    "address": "宗郷4-9-12",
    "tel": "0848-64-3824",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "八洲管理（株）",
    "zip": "733-0032",
    "city": "広島市西区",
    "address": "東観音町19-1 タルタビル2F",
    "tel": "082-232-7871",
    "url": "http://www.yashimakanri.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "ユニオン（株）",
    "zip": "729-0141",
    "city": "尾道市",
    "address": "高須町1283-1",
    "tel": "0848-29-5633",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "ユニオンフォレスト（株）",
    "zip": "737-0051",
    "city": "呉市",
    "address": "中央2-5-15",
    "tel": "0823-32-5151",
    "url": "http://www.union-forest.co.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": true,
    "traffic": false,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ユニバーサルセキュリティー",
    "zip": "723-0052",
    "city": "三原市",
    "address": "皆実3-2-5 中田ビル2F",
    "tel": "0848-61-3744",
    "url": "https://www.universalsecurity.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "鯉城総合警備（株）",
    "zip": "730-0851",
    "city": "広島市中区",
    "address": "榎町5-22 井上ビル202",
    "tel": "082-291-8090",
    "url": "https://rijyosoukei.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "リライアンス･セキュリティー（株）",
    "zip": "730-0845",
    "city": "広島市中区",
    "address": "舟入川口町14-22",
    "tel": "082-297-9588",
    "url": "https://www.reliance-s.com/page1/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": true,
    "bodyguard": true
  },
  {
    "name": "（株）relight",
    "zip": "730-0841",
    "city": "広島市中区",
    "address": "舟入町6-23",
    "tel": "082-942-4594",
    "url": "https://relight-hiroshima.com/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": false,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）リリーフ",
    "zip": "722-2102",
    "city": "尾道市",
    "address": "因島重井町1076-2",
    "tel": "0845-25-0818",
    "url": "https://kanouya.group/group/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）リリカル生長",
    "zip": "730-0045",
    "city": "広島市中区",
    "address": "鶴見町12-21 リリカルビル2F",
    "tel": "082-247-0044",
    "url": "",
    "facility": false,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）ローズ警備",
    "zip": "720-0022",
    "city": "福山市",
    "address": "奈良津町1-8-1",
    "tel": "084-924-8677",
    "url": "",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（株）ワークスタッフ中国",
    "zip": "730-0004",
    "city": "広島市中区",
    "address": "東白島町20-8",
    "tel": "082-502-3911",
    "url": "https://www.workstaff-chu.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  },
  {
    "name": "（有）ワールドクリエイトグループ",
    "zip": "731-0153",
    "city": "広島市安佐南区",
    "address": "安東1-3-13",
    "tel": "082-299-5468",
    "url": "http://world-keibi.jp/",
    "facility": true,
    "patrol": false,
    "security": false,
    "airport": false,
    "machine": false,
    "traffic": true,
    "crowd": true,
    "valuables": false,
    "bodyguard": false
  }
]

type Company = {
  name: string
  zip: string
  city: string
  address: string
  tel: string
  url: string
  facility: boolean
  patrol: boolean
  security: boolean
  airport: boolean
  machine: boolean
  traffic: boolean
  crowd: boolean
  valuables: boolean
  bodyguard: boolean
}

const serviceList = [
  { key: 'facility',  label: '施設警備',     color: '#457b9d' },
  { key: 'traffic',   label: '交通誘導警備', color: '#2a9d8f' },
  { key: 'crowd',     label: '雑踏警備',     color: '#e9c46a' },
  { key: 'machine',   label: '機械警備',     color: '#6a4c93' },
  { key: 'valuables', label: '貴重品運搬警備', color: '#e76f51' },
  { key: 'bodyguard', label: '身辺警備',     color: '#e63946' },
  { key: 'patrol',    label: '巡回警備',     color: '#1d7a8c' },
  { key: 'security',  label: '保安警備',     color: '#5c7a29' },
  { key: 'airport',   label: '空港保安警備', color: '#8b5e3c' },
]

function ServiceTag({ label, color }: { label: string; color: string }) {
  return (
    <span style={{
      fontSize: '11px', padding: '2px 8px', borderRadius: '99px',
      background: color + '22', color, fontWeight: 600,
      marginRight: '4px', marginBottom: '4px', display: 'inline-block'
    }}>
      {label}
    </span>
  )
}

export default function HiroshimaPage() {
  return (
    <main>
      <header style={{ background: '#1a1a2e', color: 'white', padding: '16px 24px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <a href="/" style={{ fontWeight: 700, fontSize: '20px', color: 'white', textDecoration: 'none' }}>keibi.online</a>
        <nav style={{ display: 'flex', gap: '24px', fontSize: '14px' }}>
          <a href="/prefecture" style={{ color: 'white', textDecoration: 'none' }}>都道府県から探す</a>
          <a href="/news" style={{ color: 'white', textDecoration: 'none' }}>ニュース</a>
          <a href="/license" style={{ color: 'white', textDecoration: 'none' }}>資格情報</a>
          <a href="/column" style={{ color: 'white', textDecoration: 'none' }}>コラム</a>
        </nav>
      </header>

      <div style={{ maxWidth: '1100px', margin: '0 auto', padding: '48px 24px' }}>
        <div style={{ fontSize: '13px', color: '#999', marginBottom: '16px' }}>
          <a href="/" style={{ color: '#999' }}>トップ</a> &gt; <a href="/prefecture" style={{ color: '#999' }}>都道府県一覧</a> &gt; 広島県
        </div>

        <h1 style={{ fontSize: '28px', fontWeight: 700, marginBottom: '8px' }}>広島県の警備会社一覧</h1>
        <p style={{ color: '#666', marginBottom: '12px' }}>{companies.length}社掲載 — 2026年6月更新</p>

        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '32px' }}>
          {serviceList.map(s => (
            <span key={s.key} style={{
              fontSize: '12px', padding: '4px 12px', borderRadius: '99px',
              background: s.color + '22', color: s.color, fontWeight: 600
            }}>{s.label}</span>
          ))}
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '12px' }}>
          {(companies as Company[]).map((c, i) => (
            <div key={i} style={{ border: '1px solid #e5e5e5', borderRadius: '12px', padding: '16px', background: 'white' }}>
              <div style={{ marginBottom: '4px' }}>
                {c.url ? (
                  <a href={c.url} target="_blank" rel="noopener noreferrer"
                    style={{ fontSize: '15px', fontWeight: 700, color: '#1a1a2e', textDecoration: 'none' }}>
                    {c.name}
                  </a>
                ) : (
                  <span style={{ fontSize: '15px', fontWeight: 700, color: '#1a1a2e' }}>{c.name}</span>
                )}
              </div>
              <div style={{ fontSize: '12px', color: '#888', marginBottom: '4px' }}>
                〒{c.zip} {c.city} {c.address}
              </div>
              <div style={{ fontSize: '12px', color: '#666', marginBottom: '10px' }}>
                📞 {c.tel}
              </div>
              <div>
                {serviceList.map(s =>
                  (c as any)[s.key] ? <ServiceTag key={s.key} label={s.label} color={s.color} /> : null
                )}
              </div>
            </div>
          ))}
        </div>
      </div>

      <footer style={{ background: '#1a1a2e', color: 'white', textAlign: 'center', padding: '32px 24px', fontSize: '14px', opacity: 0.7 }}>
        © 2026 keibi.online — 警備業界の総合情報サイト
      </footer>
    </main>
  )
}
